##################################################################################
#
# XProject Clans plugin by QuassBottle specially for Absolute Anarchy server
#
##################################################################################

clan:
  price: 5000
